# glynn,
# jekyll
name: Assert Fail
markdown: kramdown
highlighter: rouge
encoding: utf-8
url: "https://assertfail.gewalli.se"

exclude: [Gemfile, Gemfile.lock, bin, README.md, assertfail.sublime-project, requirements.txt]
plugins:
  - jekyll-seo-tag
  - jekyll-jupyter-notebook
  - jekyll-sitemap
  - jekyll-spaceship
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/